image: tevun/quasar:latest

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - quasar/node_modules/
  policy: pull-push

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval "$(ssh-agent -s)"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "${DEPLOY_SERVER_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  - git config --global user.email "ci@disk.ninja"
  - git config --global user.name "CI"
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

develop:
  only:
    - develop
  script:
    - echo "Add host ${DEVELOPMENT_DEPLOY_HOST}"
    - ssh-keyscan -H "${DEVELOPMENT_DEPLOY_HOST}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "Deploy to ${DEVELOPMENT_DEPLOY_REMOTE}"
    - bash "${PWD}/dist/stage/deploy.sh" "stage" "${DEVELOPMENT_DEPLOY_REMOTE}"

master:
  only:
    - master
  script:
    - echo "Add host ${MASTER_DEPLOY_HOST}"
    - ssh-keyscan -H "${MASTER_DEPLOY_HOST}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "Deploy to ${MASTER_DEPLOY_REMOTE}"
    - bash "${PWD}/dist/production/deploy.sh" "production" "${MASTER_DEPLOY_REMOTE}"
