POST {{host}}/api/v1/auth/login
Content-Type: application/json
Device: test

{
  "login": "admin@blueway.com",
  "password": "aq1sw2de3"
}
> {% client.global.set('authorization', response.body.data.token) %}

###
