version: '3'

# networks
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  # internal network
  internal:
    driver: bridge

# volumes
volumes:
  # MySQL data volume
  blueway-mysql_data:
    driver: local
  # Redis data volume
  blueway-redis_data:
    driver: local

# services
services:

  # database
  blueway-mysql:
    image: mysql:5.7
    container_name: blueway-mysql
    restart: always
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - blueway-mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  # Symfony service to provide api
  blueway-nginx:
    image: webdevops/php-nginx:7.3
    container_name: blueway-nginx
    restart: always
    networks:
      - internal
      - reverse-proxy
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    depends_on:
      - blueway-mysql
      - blueway-redis
    links:
      - blueway-mysql
      - blueway-redis
    environment:
      - VIRTUAL_HOST=blueway.devi.tools
      - LETSENCRYPT_HOST=blueway.devi.tools
      - LETSENCRYPT_EMAIL=wilcorrea@gmail.com
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400

  # cache
  blueway-redis:
    image: redis:4.0
    container_name: blueway-redis
    command: --appendonly yes
    networks:
      - internal
    volumes:
      - blueway-redis_data:/data

  # blueway-queue
  blueway-queue:
    image: webdevops/php-nginx:7.3
    container_name: blueway-queue
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - .docker/blueway-queue/opt/docker/etc/supervisor.d/php-fpm.conf:/opt/docker/etc/supervisor.d/php-fpm.conf
    depends_on:
      - blueway-mysql
      - blueway-redis
    links:
      - blueway-mysql
      - blueway-redis