version: '3'

# networks
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  # internal network
  internal:
    driver: bridge

# volumes
volumes:
  # MySQL data volume
  blueway-mysql_data:
    driver: local
  # Redis data volume
  blueway-redis_data:
    driver: local
  # blueway-minio-data
  blueway-minio-data:
    driver: local
  # blueway-minio-data
  blueway-minio-config:
    driver: local

# services
services:

  # nginx
  blueway-nginx:
    image: webdevops/php-nginx:7.4
    container_name: blueway-nginx
    restart: always
    networks:
      - internal
      - reverse-proxy
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - ./.docker/blueway-nginx/opt/docker/etc/nginx/vhost.common.d/10-general.conf:/opt/docker/etc/nginx/vhost.common.d/10-general.conf
    depends_on:
      - blueway-mysql
      - blueway-redis
    environment:
      - VIRTUAL_HOST=blueway.devi.tools
      - LETSENCRYPT_HOST=blueway.devi.tools
      - LETSENCRYPT_EMAIL=wilcorrea@gmail.com
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - XDEBUG_PROFILER_ENABLE=Off
      - PHP_DISPLAY_ERRORS=0
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_POST_MAX_SIZE=50M
      - PHP_UPLOAD_MAX_FILESIZE=50M

  # database
  blueway-mysql:
    image: mysql:5.7
    container_name: blueway-mysql
    restart: always
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - blueway-mysql_data:/var/lib/mysql
      - .:/var/www/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  # cache
  blueway-redis:
    image: redis:4.0
    container_name: blueway-redis
    restart: always
    command: --appendonly yes
    networks:
      - internal
    volumes:
      - blueway-redis_data:/data

  # queue
  blueway-queue:
    image: webdevops/php-nginx:7.4
    container_name: blueway-queue
    restart: always
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - .docker/blueway-queue/opt/docker/etc/supervisor.d/php-fpm.conf:/opt/docker/etc/supervisor.d/php-fpm.conf
    depends_on:
      - blueway-mysql
      - blueway-redis

  # storage
  blueway-minio:
    image: minio/minio:RELEASE.2019-02-14T00-21-45Z
    container_name: blueway-minio
    restart: always
    command: server /data
    networks:
      - internal
    volumes:
      - blueway-minio-data:/data
      - blueway-minio-config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=s20B73VI0E0164ABPXZIH
      - MINIO_SECRET_KEY=M5mTytfy7U4xsxUitNWVJjC0AvV3FwXvXZQmYXab

  # storage setup
  blueway-minio-controller:
    image: minio/mc
    container_name: blueway-minio-controller
    restart: always
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    depends_on:
      - blueway-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add server http://blueway-minio:9000 s20B73VI0E0164ABPXZIH M5mTytfy7U4xsxUitNWVJjC0AvV3FwXvXZQmYXab;
      /usr/bin/mc mb -p server/blueway;
      exit 0;
      "
